// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RetroRewindWebsite.Data;
using RetroRewindWebsite.Models.Entities.Room;

#nullable disable

namespace RetroRewindWebsite.Migrations
{
    [DbContext(typeof(LeaderboardDbContext))]
    [Migration("20261004181544_AddPlayerBadges")]
    partial class AddPlayerBadges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.Player.BadgeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Role")
                        .IsUnique();

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 61573,
                            Name = "Moderator",
                            Role = "ROLE_MODERATOR"
                        },
                        new
                        {
                            Id = 61574,
                            Name = "Creator (VanzaKart)",
                            Role = "ROLE_LEADER"
                        },
                        new
                        {
                            Id = 61575,
                            Name = "Staff Ghost",
                            Role = "ROLE_STAFF_GHOST"
                        },
                        new
                        {
                            Id = 61576,
                            Name = "Developer",
                            Role = "ROLE_DEVELOPER"
                        },
                        new
                        {
                            Id = 61577,
                            Name = "Creative Director",
                            Role = "ROLE_CREATIVE_DIRECTOR"
                        },
                        new
                        {
                            Id = 61578,
                            Name = "Translator",
                            Role = "ROLE_TRANSLATOR"
                        },
                        new
                        {
                            Id = 61579,
                            Name = "Beta Tester",
                            Role = "ROLE_BETA_TESTER"
                        });
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.Player.LegacyPlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ev")
                        .HasColumnType("integer");

                    b.Property<string>("Fc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("boolean");

                    b.Property<string>("MiiData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiiImageBase64")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Fc");

                    b.HasIndex("IsSuspicious");

                    b.HasIndex("Pid");

                    b.HasIndex("Rank");

                    b.ToTable("LegacyPlayers");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.Player.PlayerBadgeEntity", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("BadgeId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("PlayerBadges");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.Player.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ev")
                        .HasColumnType("integer");

                    b.Property<string>("Fc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FlagReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuspicious")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MiiData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Pid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PrestigeRank")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("SuspiciousVRJumps")
                        .HasColumnType("integer");

                    b.Property<string>("UnflagReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VRGainLast24Hours")
                        .HasColumnType("integer");

                    b.Property<int>("VRGainLastMonth")
                        .HasColumnType("integer");

                    b.Property<int>("VRGainLastWeek")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Fc");

                    b.HasIndex("IsSuspicious");

                    b.HasIndex("LastSeen");

                    b.HasIndex("Pid")
                        .IsUnique();

                    b.HasIndex("Rank");

                    b.HasIndex("VRGainLast24Hours");

                    b.HasIndex("VRGainLastMonth");

                    b.HasIndex("VRGainLastWeek");

                    b.HasIndex("IsSuspicious", "Ev", "LastSeen");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.Player.PlayerMiiCacheEntity", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("MiiImageBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("MiiImageFetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlayerId");

                    b.HasIndex("MiiImageFetchedAt");

                    b.ToTable("PlayerMiiCaches");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.Player.PlayerStreakEntity", b =>
                {
                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<int>("BestStreak")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LastActiveDay")
                        .HasColumnType("date");

                    b.Property<int>("LostStreak")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LostStreakLastDay")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LostStreakStartDay")
                        .HasColumnType("date");

                    b.Property<int>("RestoreMonth")
                        .HasColumnType("integer");

                    b.Property<int>("RestoresUsed")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StreakStartDay")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("VacationSince")
                        .HasColumnType("date");

                    b.HasKey("ProfileId");

                    b.HasIndex("CurrentStreak");

                    b.HasIndex("LastActiveDay");

                    b.ToTable("PlayerStreaks");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.Player.VRHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalVR")
                        .HasColumnType("integer");

                    b.Property<int>("VRChange")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PlayerId", "Date");

                    b.ToTable("VRHistories");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.RaceResult.RaceResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("CharacterId")
                        .HasColumnType("smallint");

                    b.Property<short>("CourseId")
                        .HasColumnType("smallint");

                    b.Property<short>("EngineClassId")
                        .HasColumnType("smallint");

                    b.Property<short>("FinishPos")
                        .HasColumnType("smallint");

                    b.Property<int>("FinishTime")
                        .HasColumnType("integer");

                    b.Property<int>("FramesIn1st")
                        .HasColumnType("integer");

                    b.Property<short>("PlayerCount")
                        .HasColumnType("smallint");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<int>("RaceNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RaceTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<short>("VehicleId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CourseId");

                    b.HasIndex("ProfileId");

                    b.HasIndex("RaceTimestamp");

                    b.HasIndex("VehicleId");

                    b.HasIndex("CourseId", "EngineClassId");

                    b.HasIndex("CourseId", "FinishTime");

                    b.HasIndex("ProfileId", "CharacterId");

                    b.HasIndex("ProfileId", "CourseId");

                    b.HasIndex("ProfileId", "RaceTimestamp");

                    b.HasIndex("ProfileId", "VehicleId");

                    b.HasIndex("RoomId", "RaceNumber", "ProfileId")
                        .IsUnique()
                        .HasDatabaseName("IX_RaceResults_RoomId_RaceNumber_ProfileId");

                    b.ToTable("RaceResults");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.Room.RoomSnapshotEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PrivateRooms")
                        .HasColumnType("integer");

                    b.Property<int>("PublicRooms")
                        .HasColumnType("integer");

                    b.Property<List<RoomData>>("Rooms")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("RoomSnapshots");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.TimeTrial.GhostSubmissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("CC")
                        .HasColumnType("smallint");

                    b.Property<short>("CharacterId")
                        .HasColumnType("smallint");

                    b.Property<short>("ControllerType")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("DateSet")
                        .HasColumnType("date");

                    b.Property<short>("DriftCategory")
                        .HasColumnType("smallint");

                    b.Property<short>("DriftType")
                        .HasColumnType("smallint");

                    b.Property<string>("FinishTimeDisplay")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FinishTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("GhostFilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Glitch")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFlap")
                        .HasColumnType("boolean");

                    b.Property<short>("LapCount")
                        .HasColumnType("smallint");

                    b.PrimitiveCollection<string>("LapSplitsMs")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MiiName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Shroomless")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TTProfileId")
                        .HasColumnType("integer");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.Property<short>("VehicleId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("SubmittedAt");

                    b.HasIndex("TTProfileId");

                    b.HasIndex("TrackId");

                    b.HasIndex("TrackId", "CC");

                    b.HasIndex("TrackId", "CC", "DateSet");

                    b.HasIndex("TrackId", "CC", "FinishTimeMs");

                    b.HasIndex("TrackId", "CC", "Glitch");

                    b.HasIndex("TrackId", "CC", "Glitch", "FinishTimeMs", "SubmittedAt");

                    b.ToTable("GhostSubmissions");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.TimeTrial.TTProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentWorldRecords")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TotalSubmissions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("TTProfiles");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.TimeTrial.TrackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<short>("CourseId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<short>("Laps")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("SupportsGlitch")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("SupportsGlitch");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.Player.PlayerBadgeEntity", b =>
                {
                    b.HasOne("RetroRewindWebsite.Models.Entities.Player.BadgeEntity", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetroRewindWebsite.Models.Entities.Player.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.Player.PlayerMiiCacheEntity", b =>
                {
                    b.HasOne("RetroRewindWebsite.Models.Entities.Player.PlayerEntity", "Player")
                        .WithOne("MiiCache")
                        .HasForeignKey("RetroRewindWebsite.Models.Entities.Player.PlayerMiiCacheEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.Player.VRHistoryEntity", b =>
                {
                    b.HasOne("RetroRewindWebsite.Models.Entities.Player.PlayerEntity", "Player")
                        .WithMany("VRHistory")
                        .HasForeignKey("PlayerId")
                        .HasPrincipalKey("Pid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.TimeTrial.GhostSubmissionEntity", b =>
                {
                    b.HasOne("RetroRewindWebsite.Models.Entities.TimeTrial.TTProfileEntity", "TTProfile")
                        .WithMany("GhostSubmissions")
                        .HasForeignKey("TTProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RetroRewindWebsite.Models.Entities.TimeTrial.TrackEntity", "Track")
                        .WithMany("GhostSubmissions")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TTProfile");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.Player.PlayerEntity", b =>
                {
                    b.Navigation("MiiCache");

                    b.Navigation("VRHistory");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.TimeTrial.TTProfileEntity", b =>
                {
                    b.Navigation("GhostSubmissions");
                });

            modelBuilder.Entity("RetroRewindWebsite.Models.Entities.TimeTrial.TrackEntity", b =>
                {
                    b.Navigation("GhostSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
